### ISSUE TITLE
Rare case of collision when do multiples request/reply

### ISSUE THREAD

**Issue by YiuRULE** [nats-io/nats.py#187]
Hi !

We are currently using the library (and thanks for the work of the contributor of the project !), and it seems when we do multiples REQ/REPLY on the same time from the client, similar at:

```
async def a(nc):
    msg = nc.request(subject="foo", payload={})
    # Do something with msg

async def b(nc):
    msg = nc.request(subject="bar", payload={})
    # Do something with msg  

await asyncio.gather(
    a(nc),
    b(nc),
)
```

We could send, on a really rare case, the same reply id to the server, who make the function `b`, receive the response from the request `a`.

Concerning our log, from the server side:

```
2020-11-09 14:17:19 ... Message(subject='foo', reply='_INBOX.Kjq4GobYoPqdOsTvlGKcbf.Kjq4GobYoPqdOuTvlGKcbf', ...)
2020-11-09 14:17:19 ... Message(subject='bar', reply='_INBOX.Kjq4GobYoPqdOsTvlGKcbf.Kjq4GobYoPqdOuTvlGKcbf', ...)
```

Concerning the environment we found the id collision, it was during internal benchmark for our application, where we had our API connecting with a nats server, as a reply and as a publisher, and an another server who spawn 1 new client each second and do two request at startup, while receiving message continuously.

**Comment by YiuRULE** [comment]
(if it can help, here a bit the stacktrace of the issue I had recently for the same issue)

```
  File "/home/guillaume/.virtualenvs/pykouze/lib/python3.8/site-packages/nats/aio/client.py", line 943, in request
    del self._resp_map[token.decode()]
KeyError: 'qnaUryOVxMvt2AiVJpzTik'
```

**Comment by YiuRULE** [comment]
Sorry, again me :)

Got a bit of time, and worker on a code who could reproduce the bug, who reproduce a similar environment on how we use the library.

client.py
```
import asyncio
from nats.aio.client import Client as NATS


async def run():
    nc = NATS()
    await nc.connect("nats://localhost:4222")

    await nc.request("hello", b'', timeout=1)
    await asyncio.gather(
        nc.request("foo", b'', timeout=1),
        nc.request("bar", b'', timeout=1),
    )

asyncio.run(run())
```

server.py
```
import asyncio
from nats.aio.client import Client as NATS


async def run():
    nc = NATS()
    await nc.connect("nats://localhost:4222")

    async def dummy(msg):
        await nc.publish(msg.reply, b'')

    await nc.subscribe("hello", cb=dummy)
    await nc.subscribe("foo", cb=dummy)
    await nc.subscribe("bar", cb=dummy)

    while True:
        await asyncio.sleep(1)

asyncio.run(run())
```

Server should be run one time, while the client should be run like this using bash or an another shell `while :; do python3 client.py; done`, could take some time, but one time, an exception would be launched by the client.

**Comment by charliestrawn** [comment]
Hi @YiuRULE, sorry for the wait. I will take a look at this.

**Comment by Smerity** [comment]
Thanks @YiuRULE for noting the issue and producing code that reproduces the bug. I have run into the same issue and checked here to see if someone else had saved me from the work and the bug reproduces cleanly for me after a little wait <3

I have run into this in issue as well but rather than spawning multiple clients rapidly it was a single client with multiple in-flight requests. The issue appeared when hitting ~100 concurrent requests but not with ~50.

Happy to test any potential bug fixes or do bug chasing if that's helpful. Thanks for checking the issue out @charliestrawn =]

---

Out of curiousity I ran [nuid.py](https://github.com/nats-io/nats.py/blob/9f69047a5ad6ad031bbc503cdf311f0338ad81a7/nats/aio/nuid.py) on a loop to see if it'd spit out a duplicate and that doesn't seem like it. That was likely already checked before but I just wanted to run the experiment to make my laptop warm ^_^

The issue may be an underlying race condition between the three `del self._resp_map[token]` calls, specifically that the `request`'s `asyncio.TimeoutError` also triggers `wait_for_msg`'s `asyncio.CancelledError` or similar. Commenting out the two `del` calls in `wait_for_msgs` prevents reproduction of the bug. I can't work out why that would be however.

Adding an `if token in self._resp_map` guard before each `del` prevents the issue from occurring in my local setup. `concurrent.futures._base.TimeoutError` and `nats.aio.errors.ErrTimeout` exceptions occur at about the same frequency as the `KeyError` would have.

I don't think that'd result in any larger issues either as each call is essentially performing garbage collection. If an `if` fails then it just means the garbage has already been collected by someone else.

Happy to submit a pull request with the given fix. My only concern is that I don't understand the rest of the codebase enough to be fully confident in my "garbage collection cleanup" assumption in the previous paragraph.

**Comment by charliestrawn** [comment]
Hey @Smerity thanks for the additional info and due diligence! I have not had a chance to really sink my teeth into this yet with holidays and all, but I was able to reproduce it locally using @YiuRULE's example. 

I am suspicious that the KeyError is a symptom and not the cause the async timeout when processing. I believe you're right that there should be no issue safely deleting those with `if/in` or `map.pop(key, None)` as is done elsewhere. I plan to keep digging, but if you discover anything new definitely share or PR, any and all help is greatly appreciated.

**Comment by sevaho** [comment]
Having the same issue.

When running the same example as @YiuRULE but with the following client.py as code:

```
import asyncio
from nats.aio.client import Client as NATS


async def run():
    nc = NATS()
    await nc.connect("nats://localhost:4222")

    await nc.request("hello", b'', timeout=1)
    await nc.request("foo", b'', timeout=1)
    await nc.request("bar", b'', timeout=1)

asyncio.run(run())
```

When running 5 instances of this in different terminals with following command: `while :; do python3 client.py; done` , I don't get the error.

So it is related to running inside `asyncio gather`?

**Comment by sevaho** [comment]
I think this is related as well (it happend at the same time), when running with nkeys I'm also getting the following error:

```
'Permissions Violation for Publish to "_INBOX.NhofyqbnrPcd58ANlEE2Sj.NhofyqbnrPcd58RNlEE2Sj"'
```

The client already got a response, but the server sends one again and thus fails.

nats config:

```
    {
      nkey: <NKEY>, permissions: {
        subscribe: {
          allow: "*"
        }
        allow_responses: true
      }
    }
```

**Comment by sevaho** [comment]
We are circumventing this (not a fix at all) with https://github.com/litl/backoff and works like a charm.

**Comment by Smerity** [comment]
Really excited to see #219 @wallyqs - thanks! ^_^

**Comment by wallyqs** [comment]
Fixed via #219

**Comment by Gr1N** [comment]
@wallyqs thanks for the fix, but maybe it's possible to release version 0.11.5 with backport of the fix?

**Comment by wallyqs** [comment]
sounds good, ok will backport

**Comment by wallyqs** [comment]
sounds good, ok will backport

**Comment by vshender** [comment]
I'm sorry, but this fix doesn't solve the problem, I've described it in detail in the comments to the [MR](https://github.com/nats-io/nats.py/pull/219).

**Comment by mriedem** [comment]
This issue, or maybe something related, seems to be present still in 2.1.0.

We were hitting some TimeoutErrors in an exponential backoff loop trying to submit a request (network issues presumably). Eventually `request` raised a KeyError, here is a snip of the traceback:

```
res = await client.request(topic, msg, timeout=timeout)\n  File \"/home/auckland/.virtualenvs/dispatcher/lib64/python3.8/site-packages/nats/aio/client.py\", line 899, in request\n    msg = await self._request_new_style(\n  File \"/home/auckland/.virtualenvs/dispatcher/lib64/python3.8/site-packages/nats/aio/client.py\", line 937, in _request_new_style\n    self._resp_map.pop(token.decode())\nKeyError: '<redacted>'\n"
```

I see that #219 changed `pop` to be graceful if the entry wasn't in the dict:

>self._resp_map.pop(token.decode(), None)

And that was reverted in #229, but we can apparently still hit a KeyError here:

https://github.com/nats-io/nats.py/blob/v2.1.0/nats/aio/client.py#L937

I won't profess to understand the internals of the library for how this can happen, but there is apparently still a race condition that's possible here on the latest release. Should this issue be re-opened? Should I open a new issue referencing this one? I don't really want to add KeyError handling in our code calling `request` but it crashed the app so we might need to for the time being.

**Comment by wallyqs** [comment]
Thanks @mriedem for the report, let's open a new issue since this might be to address a race and the original issue here was a wrong division producing duplicated results sometimes.
